name: GitHub Actions Events Demo
run-name: GitHub Actions Events
on: 
  workflow_dispatch:
jobs:
  Get-Environment-Variables:
    runs-on: ubuntu-latest
    steps:
    - name: Read environment variables
      run: |
        echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
        echo "GITHUB_SHA: ${{ github.sha }}"
        echo "GITHUB_REF: ${{ github.ref }}"
        echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
