name: GitHub Actions repository_dispatch Demo
run-name: GitHub Actions repository_dispatch Events
on:
  repository_dispatch:
    types: [demo]
jobs:
  dump-event:
    runs-on: ubuntu-latest
    steps:
      - name: Dump full event payload (for debugging)
        run: echo '${{ toJson(github.event) }}'
  Get-Environment-Variables:
    runs-on: ubuntu-latest
    steps:
    - name: Read environment variables
      run: |
        echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
    - name: Parsing client payload message
      run: |
        echo $MESSAGE
      env:
        MESSAGE: ${{ github.event.client_payload.message }}
